### ISSUE TITLE
have error : Action @show not defined

### ISSUE THREAD

**Issue by olipiskandar** [crip-laravel/filesys#8]
can you help me ?

**Comment by tahq69** [comment]
Please read full [installaltion ](https://github.com/crip-laravel/filesys#installation) section and make sure you registered routes for package. You can check them by calling `php artisan route:list`
You should see something like this:
![image](https://user-images.githubusercontent.com/7248215/38767331-dc055b2a-3fe7-11e8-94c6-6593a05e8dd1.png)

If it does not helps, please provide me more details of the error.

**Comment by olipiskandar** [comment]
![screen shot 2018-04-14 at 17 43 03](https://user-images.githubusercontent.com/4706142/38767441-4dda5746-400b-11e8-83a1-c25755318c08.png)

**Comment by tahq69** [comment]
Routes are in place. Please provide more details about error.

**Comment by olipiskandar** [comment]
when i try install the package, i got some notice from cli : 
`Failed to execute unzip -qq  '/Users/olipiskandar/Desktop/testimage/vendor/crip-laravel/filesys/f7b63e21eb7d7e6bab3c60e4a35c7b7f' -d '/Users/olipiskandar/Desktop/testimage/vendor/composer/b39dd18f'

error:  cannot create /Users/olipiskandar/Desktop/testimage/vendor/composer/b39dd18f/crip-laravel-filesys-bdb859e/tests/stubs/�����������������.jpg
        Illegal byte sequence
`
and i got error : 

![screen shot 2018-04-14 at 17 49 27](https://user-images.githubusercontent.com/4706142/38767484-67cd4d92-400c-11e8-8398-99b4b2aff856.png)

**Comment by tahq69** [comment]
It seems you have some issues with encoding in your system. I have test file with Cyrillic characters in name to make sure this kind of files works in file manager. But this should not affect routing as it is fully in Latin.

Please add full stack trace of the error as I need understated the source of error.

**Comment by olipiskandar** [comment]
InvalidArgumentException thrown with message "Action @show not defined."

Stacktrace:
#36 InvalidArgumentException in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:403
#35 Illuminate\Routing\UrlGenerator:action in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:92
#34 action in /Users/olipiskandar/Desktop/testimage/vendor/crip-laravel/filesys/src/App/Controllers/ManagerController.php:21
#33 Crip\Filesys\App\Controllers\ManagerController:__invoke in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
#32 call_user_func_array in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
#31 Illuminate\Routing\Controller:callAction in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
#30 Illuminate\Routing\ControllerDispatcher:dispatch in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Routing/Route.php:212
#29 Illuminate\Routing\Route:runController in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Routing/Route.php:169
#28 Illuminate\Routing\Route:run in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Routing/Router.php:659
#27 Illuminate\Routing\Router:Illuminate\Routing\{closure} in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#26 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
#25 Illuminate\Pipeline\Pipeline:then in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Routing/Router.php:661
#24 Illuminate\Routing\Router:runRouteWithinStack in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Routing/Router.php:636
#23 Illuminate\Routing\Router:runRoute in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Routing/Router.php:602
#22 Illuminate\Routing\Router:dispatchToRoute in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Routing/Router.php:591
#21 Illuminate\Routing\Router:dispatch in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
#20 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#19 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Users/olipiskandar/Desktop/testimage/vendor/fideloper/proxy/src/TrustProxies.php:57
#18 Fideloper\Proxy\TrustProxies:handle in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#17 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#16 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
#15 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#14 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#13 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
#12 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#11 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#10 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
#9 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#8 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#7 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:46
#6 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#5 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#4 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
#3 Illuminate\Pipeline\Pipeline:then in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
#2 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /Users/olipiskandar/Desktop/testimage/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#1 Illuminate\Foundation\Http\Kernel:handle in /Users/olipiskandar/Desktop/testimage/public/index.php:55
#0 require_once in /Users/olipiskandar/Desktop/testimage/server.php:21

**Comment by tahq69** [comment]
Seems there is some issue with configuration file load/read. Action should contain full namespace to the package controller, but it not.

Could you please provide a full contents from your `/Users/olipiskandar/Desktop/testimage/config/cripfilesys.php` file and some debug info of the package. You can get it by addign `dd($this->package);` before line 21 in `/Users/olipiskandar/Desktop/testimage/vendor/crip-laravel/filesys/src/App/Controllers/ManagerController.php`. Something like this:
![image](https://user-images.githubusercontent.com/7248215/38808555-539600a2-4189-11e8-90c6-398ccee20521.png)

And then request manager and provide that info: 
![image](https://user-images.githubusercontent.com/7248215/38808662-a59702c0-4189-11e8-92d5-7fa4f23118be.png)

**Comment by olipiskandar** [comment]
thanks... its work...
just run composer dumpautoload
